# Generated by Django 5.2.7 on 2026-04-03 09:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('country_pause', 'Country Pause (0 closes after N leads)'), ('type_deprioritize', 'Lead Type Deprioritize (<0.5% close rate)'), ('source_reduce', 'Source Reduce (<1% reply rate)'), ('domain_rotate', 'Domain Rotate (low open rate)')], max_length=30)),
                ('dimension_value', models.CharField(help_text='The country, lead type, source, or domain being excluded', max_length=255)),
                ('reason', models.TextField()),
                ('leads_contacted', models.IntegerField(default=0)),
                ('metric_value', models.FloatField(default=0, help_text='The close rate, reply rate, or open rate that triggered exclusion')),
                ('is_active', models.BooleanField(default=True)),
                ('overridden', models.BooleanField(default=False, help_text='Manually overridden by admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_emailed', models.IntegerField(default=0)),
                ('total_forms_filled', models.IntegerField(default=0)),
                ('total_replies', models.IntegerField(default=0)),
                ('total_interested', models.IntegerField(default=0)),
                ('total_closed', models.IntegerField(default=0)),
                ('by_country', models.JSONField(default=dict)),
                ('by_lead_type', models.JSONField(default=dict)),
                ('by_source', models.JSONField(default=dict)),
                ('by_channel', models.JSONField(default=dict)),
                ('exclusions_applied', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('has_contact_form', models.BooleanField(default=False)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('lead_type', models.CharField(choices=[('voip_provider', 'VoIP Provider'), ('mno', 'MNO'), ('mvno', 'MVNO'), ('call_center', 'Call Center / BPO'), ('ucaas', 'UCaaS Provider'), ('ccaas', 'CCaaS Provider'), ('reseller', 'Wholesale Reseller'), ('itsp', 'ITSP')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn (Apollo)'), ('google_search', 'Google Search'), ('google_maps', 'Google Maps'), ('directory', 'Telecom Directory'), ('conference', 'Conference List')], db_index=True, max_length=20)),
                ('keyword_used', models.CharField(blank=True, max_length=255)),
                ('company_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('score', models.IntegerField(default=0, help_text='AI quality score 0-100')),
                ('email_sent', models.BooleanField(default=False)),
                ('form_filled', models.BooleanField(default=False)),
                ('email_opened', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('interested', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('revenue_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequence_stage', models.IntegerField(default=0, help_text='Which email in the sequence (0=not started, 1-4)')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', 'lead_type'], name='leads_lead_country_fe5173_idx'), models.Index(fields=['source', 'keyword_used'], name='leads_lead_source_2a91d3_idx'), models.Index(fields=['score'], name='leads_lead_score_016ea8_idx'), models.Index(fields=['replied'], name='leads_lead_replied_477b4e_idx'), models.Index(fields=['closed'], name='leads_lead_closed_691e7d_idx'), models.Index(fields=['sequence_stage', 'next_followup_at'], name='leads_lead_sequenc_22b007_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('form', 'Contact Form')], max_length=10)),
                ('sequence_stage', models.IntegerField(help_text='1=intro, 2=quality, 3=social proof, 4=breakup')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message_body', models.TextField(blank=True)),
                ('sending_domain', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='leads.lead')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceExhaustionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn (Apollo)'), ('google_search', 'Google Search'), ('google_maps', 'Google Maps'), ('directory', 'Telecom Directory'), ('conference', 'Conference List')], max_length=20)),
                ('keyword', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('lead_type', models.CharField(blank=True, choices=[('voip_provider', 'VoIP Provider'), ('mno', 'MNO'), ('mvno', 'MVNO'), ('call_center', 'Call Center / BPO'), ('ucaas', 'UCaaS Provider'), ('ccaas', 'CCaaS Provider'), ('reseller', 'Wholesale Reseller'), ('itsp', 'ITSP')], max_length=20)),
                ('total_found', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted'), ('paused', 'Paused')], default='active', max_length=20)),
                ('last_scraped', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_scraped'],
                'unique_together': {('source', 'keyword', 'country', 'city', 'lead_type')},
            },
        ),
    ]
