# Generated by Django 5.2.7 on 2026-04-03 10:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmtpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('daily_limit', models.IntegerField(default=100, help_text='Max emails per day from this connection')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('leads', models.ManyToManyField(blank=True, related_name='lead_lists', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('scheduled', 'Scheduled'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('subject', models.CharField(default='', max_length=500)),
                ('body', models.TextField(default='', help_text='Use {{firstName}}, {{lastName}}, {{company}}, {{email}} for personalization')),
                ('send_option', models.CharField(choices=[('now', 'Send Now'), ('later', 'Schedule for Later')], default='now', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, help_text='Comma-separated CC emails')),
                ('bcc', models.TextField(blank=True, help_text='Comma-separated BCC emails')),
                ('total_recipients', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_replied', models.IntegerField(default=0)),
                ('total_bounced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.emailtemplate')),
                ('lead_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='leads.leadlist')),
                ('smtp_connection', models.ForeignKey(blank=True, help_text='Leave blank for auto-select', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.smtpconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
