# Generated by Django 6.0.3 on 2026-04-07 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_emailtemplate_smtpconnection_leadlist_emailcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('apollo', 'Apollo'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('company_name', models.CharField(max_length=500)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('emails', models.JSONField(default=list)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('keyword_category', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('apollo', 'Apollo'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('master', 'Master')], max_length=20)),
                ('search_params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('lead_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=500)),
                ('website', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('logs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_tasks', to='leads.masterlead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='masterlead',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.searchsession'),
        ),
    ]
